### ISSUE TITLE
Crash on startup [1.14]

### ISSUE THREAD

**Issue by cryum** [NerdHubMC/Player-Graves#8] opened 2019-08-20 13:34 UTC
[crash-2019-08-20_21.32.58-client.txt](https://github.com/NerdHubMC/Player-Graves/files/3520861/crash-2019-08-20_21.32.58-client.txt)

Only other mods are general api/dependency mods

**Comment by UpcraftLP** [comment] 2019-08-20 19:31
duplicate of #4

**Closed as completed by UpcraftLP** 2019-08-20 19:31 UTC
Labels: duplicate
